import os

DEFAULT_PLANNER_MODEL = "qwen2.5:1.5b"
DEFAULT_ROUTER_MODEL = "qwen2.5:1.5b"
DEFAULT_RESEARCH_MODEL = "qwen2.5:3b"
DEFAULT_MEMORY_MODEL = "qwen2.5:1.5b"
DEFAULT_CODE_MODEL = "qwen2.5-coder:1.5b"
DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"

DEFAULT_PLANNER_TIMEOUT_SECONDS = 6.0
DEFAULT_RESEARCH_TIMEOUT_SECONDS = 12.0
DEFAULT_MEMORY_TIMEOUT_SECONDS = 8.0
DEFAULT_RESEARCH_MAX_FILES = 4
DEFAULT_RESEARCH_MAX_CHARS_PER_FILE = 3500
DEFAULT_RESEARCH_MAX_TOTAL_CHARS = 12000

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")

FRIDAY_PLANNER_MODEL = (
    os.environ.get("FRIDAY_PLANNER_MODEL")
    or os.environ.get("OLLAMA_PLANNER_MODEL")
    or DEFAULT_PLANNER_MODEL
)
FRIDAY_ROUTER_MODEL = os.environ.get("FRIDAY_ROUTER_MODEL", DEFAULT_ROUTER_MODEL)
FRIDAY_RESEARCH_MODEL = os.environ.get("FRIDAY_RESEARCH_MODEL", DEFAULT_RESEARCH_MODEL)
FRIDAY_MEMORY_MODEL = os.environ.get("FRIDAY_MEMORY_MODEL", DEFAULT_MEMORY_MODEL)
FRIDAY_CODE_MODEL = os.environ.get("FRIDAY_CODE_MODEL", DEFAULT_CODE_MODEL)
FRIDAY_EMBEDDING_MODEL = os.environ.get("FRIDAY_EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)

FRIDAY_PLANNER_TIMEOUT_SECONDS = float(
    os.environ.get("FRIDAY_PLANNER_TIMEOUT_SECONDS", str(DEFAULT_PLANNER_TIMEOUT_SECONDS))
)
FRIDAY_RESEARCH_TIMEOUT_SECONDS = float(
    os.environ.get("FRIDAY_RESEARCH_TIMEOUT_SECONDS", str(DEFAULT_RESEARCH_TIMEOUT_SECONDS))
)
FRIDAY_MEMORY_TIMEOUT_SECONDS = float(
    os.environ.get("FRIDAY_MEMORY_TIMEOUT_SECONDS", str(DEFAULT_MEMORY_TIMEOUT_SECONDS))
)
FRIDAY_RESEARCH_MAX_FILES = int(
    os.environ.get("FRIDAY_RESEARCH_MAX_FILES", str(DEFAULT_RESEARCH_MAX_FILES))
)
FRIDAY_RESEARCH_MAX_CHARS_PER_FILE = int(
    os.environ.get("FRIDAY_RESEARCH_MAX_CHARS_PER_FILE", str(DEFAULT_RESEARCH_MAX_CHARS_PER_FILE))
)
FRIDAY_RESEARCH_MAX_TOTAL_CHARS = int(
    os.environ.get("FRIDAY_RESEARCH_MAX_TOTAL_CHARS", str(DEFAULT_RESEARCH_MAX_TOTAL_CHARS))
)
