import os

DEFAULT_PLANNER_MODEL = "qwen2.5:1.5b"
DEFAULT_ROUTER_MODEL = "qwen2.5:1.5b"
DEFAULT_RESEARCH_MODEL = "qwen2.5:3b"
DEFAULT_MEMORY_MODEL = "qwen2.5:1.5b"
DEFAULT_CODE_MODEL = "qwen2.5-coder:1.5b"
DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"
DEFAULT_MEMORY_BACKEND = "sqlite"
DEFAULT_MEMORY_DB_PATH = ".friday/memory/friday_memory.sqlite3"
DEFAULT_LLM_PROVIDER = "deepseek"
DEFAULT_DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEFAULT_DEEPSEEK_MODEL = "deepseek-v4-flash"
DEFAULT_DEEPSEEK_TIMEOUT_SECONDS = 30.0
DEFAULT_ENABLE_LOCAL_LLM = False
DEFAULT_OLLAMA_MODEL = DEFAULT_PLANNER_MODEL

DEFAULT_PLANNER_TIMEOUT_SECONDS = 6.0
DEFAULT_RESEARCH_TIMEOUT_SECONDS = 12.0
DEFAULT_MEMORY_TIMEOUT_SECONDS = 8.0
DEFAULT_RESEARCH_MAX_FILES = 4
DEFAULT_RESEARCH_MAX_CHARS_PER_FILE = 3500
DEFAULT_RESEARCH_MAX_TOTAL_CHARS = 12000
DEFAULT_MEMORY_SUMMARY_MAX_CHARS = 1200
DEFAULT_MEMORY_PREVIEW_MAX_CHARS = 2000

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", DEFAULT_OLLAMA_MODEL)
LLM_PROVIDER = os.environ.get("LLM_PROVIDER", DEFAULT_LLM_PROVIDER).lower()
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", DEFAULT_DEEPSEEK_BASE_URL)
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", DEFAULT_DEEPSEEK_MODEL)
DEEPSEEK_TIMEOUT_SECONDS = float(
    os.environ.get("DEEPSEEK_TIMEOUT_SECONDS", str(DEFAULT_DEEPSEEK_TIMEOUT_SECONDS))
)
ENABLE_LOCAL_LLM = os.environ.get("ENABLE_LOCAL_LLM", str(DEFAULT_ENABLE_LOCAL_LLM)).strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

FRIDAY_PLANNER_MODEL = (
    os.environ.get("FRIDAY_PLANNER_MODEL")
    or os.environ.get("OLLAMA_PLANNER_MODEL")
    or DEFAULT_PLANNER_MODEL
)
FRIDAY_ROUTER_MODEL = os.environ.get("FRIDAY_ROUTER_MODEL", DEFAULT_ROUTER_MODEL)
FRIDAY_RESEARCH_MODEL = os.environ.get("FRIDAY_RESEARCH_MODEL", DEFAULT_RESEARCH_MODEL)
FRIDAY_MEMORY_MODEL = os.environ.get("FRIDAY_MEMORY_MODEL", DEFAULT_MEMORY_MODEL)
FRIDAY_CODE_MODEL = os.environ.get("FRIDAY_CODE_MODEL", DEFAULT_CODE_MODEL)
FRIDAY_EMBEDDING_MODEL = os.environ.get("FRIDAY_EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL)
FRIDAY_MEMORY_BACKEND = os.environ.get("FRIDAY_MEMORY_BACKEND", DEFAULT_MEMORY_BACKEND).lower()
FRIDAY_MEMORY_DB_PATH = os.environ.get("FRIDAY_MEMORY_DB_PATH", DEFAULT_MEMORY_DB_PATH)

FRIDAY_PLANNER_TIMEOUT_SECONDS = float(
    os.environ.get("FRIDAY_PLANNER_TIMEOUT_SECONDS", str(DEFAULT_PLANNER_TIMEOUT_SECONDS))
)
FRIDAY_RESEARCH_TIMEOUT_SECONDS = float(
    os.environ.get("FRIDAY_RESEARCH_TIMEOUT_SECONDS", str(DEFAULT_RESEARCH_TIMEOUT_SECONDS))
)
FRIDAY_MEMORY_TIMEOUT_SECONDS = float(
    os.environ.get("FRIDAY_MEMORY_TIMEOUT_SECONDS", str(DEFAULT_MEMORY_TIMEOUT_SECONDS))
)
FRIDAY_RESEARCH_MAX_FILES = int(
    os.environ.get("FRIDAY_RESEARCH_MAX_FILES", str(DEFAULT_RESEARCH_MAX_FILES))
)
FRIDAY_RESEARCH_MAX_CHARS_PER_FILE = int(
    os.environ.get("FRIDAY_RESEARCH_MAX_CHARS_PER_FILE", str(DEFAULT_RESEARCH_MAX_CHARS_PER_FILE))
)
FRIDAY_RESEARCH_MAX_TOTAL_CHARS = int(
    os.environ.get("FRIDAY_RESEARCH_MAX_TOTAL_CHARS", str(DEFAULT_RESEARCH_MAX_TOTAL_CHARS))
)
FRIDAY_MEMORY_SUMMARY_MAX_CHARS = int(
    os.environ.get("FRIDAY_MEMORY_SUMMARY_MAX_CHARS", str(DEFAULT_MEMORY_SUMMARY_MAX_CHARS))
)
FRIDAY_MEMORY_PREVIEW_MAX_CHARS = int(
    os.environ.get("FRIDAY_MEMORY_PREVIEW_MAX_CHARS", str(DEFAULT_MEMORY_PREVIEW_MAX_CHARS))
)
